export const EMAIL_VERIFICATION_COOKIE = "VERIFY_EMAIL";
export const AUTH_TOKEN_COOKIE = "AUTH_JWT";

export const OAUTH_STATE_COOKIE = "OAUTH_STATE";
export const OAUTH_PKCE_VERIFIER_COOKIE = "OAUTH_PKCE_VERIFIER";
